name: Docker Build

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
      - '*'
  pull_request:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine repository info
        id: repo
        run: |
          # Extract organization/user and repo name from owner/repo format
          ORG_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f1)
          APP_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          echo "ORG_NAME=${ORG_NAME}" >> $GITHUB_ENV
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
          echo "Repository: ${ORG_NAME}/${APP_NAME}"

      - name: Determine tag
        id: vars
        run: |
          REF_TYPE=${GITHUB_REF_TYPE}
          REF_NAME=${GITHUB_REF_NAME}

          if [ "$REF_TYPE" = "tag" ]; then
            TAG=${REF_NAME#v}  # remove 'v' prefix if present
          elif [ "$REF_NAME" = "main" ]; then
            TAG="latest"
          else
            TAG=$(echo "$REF_NAME" | tr '/' '-')
          fi

          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag ${APP_NAME}:${TAG} .

      - name: Push image
        run: |
          docker tag ${APP_NAME}:${TAG} ${ORG_NAME}/${APP_NAME}:${TAG}
          docker push ${ORG_NAME}/${APP_NAME}:${TAG}